#!/usr/bin/env ruby
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

Mailman::Application.run do
  default do
    dmarc = Dmarc::Email.new(message).report
    return unless dmarc

    Record.save_dmarc(dmarc)
  end
end
